### ISSUE TITLE
gettext for strings with variables

### ISSUE THREAD

**Issue by citizen-stig** [mrjoes/flask-admin#26]
Please take a look at WTForms issue https://github.com/wtforms/wtforms/issues/261, it may be related to the Flask-Admin implementation of the gettext

**Comment by mrjoes** [comment]
Indeed, it was a problem in Flask-Admin.

Flask-Admin uses Flask-Babel implementation and Flask-Babel can format string right away with `**kwargs`. Default Babel domain does not do formatting. Flask-Admin was passing Flask-Babel version of the API and WTForms crashed.

Fixed in main repo (https://github.com/flask-admin/flask-admin)

**Comment by citizen-stig** [comment]
Thank you for a quick response!
